---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-service-config-map
  namespace: dev-marvel
data:
  application.yml: |
    server:
      port: 8086

    spring:
      servlet:
        multipart.max-file-size: 10MB
      application:
        name: resource-service

    logging:
      level:
        root: info
