---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-marvel

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Secret
metadata:
  name: persistence-secrets
  namespace: dev-marvel
data:
  song_db_user: cGc=
  song_db_password: cGc=
  resource_db_user: cGc=
  resource_db_password: cGc=
