---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-pg-pv
  labels:
    db: resource-db
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /Users/Shared/k8s-resource-pg
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-db
  namespace: dev-marvel
spec:
  serviceName: resource-db-service
  replicas: 1
  selector:
    matchLabels:
      app: resource-db
  template:
    metadata:
      labels:
        app: resource-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: pg
            - name: POSTGRES_PASSWORD
              value: pg
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: resource-pg
              mountPath: /var/lib/postgresql/data
            - name: testfile
              mountPath: /config
      volumes:
        - name: testfile
          configMap:
            name: resource-service-config-map
            items:
              - key: application.yml
                path: application.yml
  volumeClaimTemplates:
    - metadata:
        name: resource-pg
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        resources:
          requests:
            storage: 512Mi
        selector:
          matchLabels:
            db: resource-db

---
apiVersion: v1
kind: Service
metadata:
  name: resource-db
  namespace: dev-marvel
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30005
  selector:
    app: resource-db
