---
apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: dev-marvel
spec:
  type: NodePort
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8086
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: dev-marvel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service
          image: johnsallison/song-service:latest