---
apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: dev-marvel
spec:
  type: NodePort
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8086
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: dev-marvel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service
          image: johnsallison/song-service:0.1
          env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: persistence-secrets
                  key: song_db_user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: persistence-secrets
                  key: song_db_password
          volumeMounts:
            - name: song-service-app-config
              mountPath: /config
          livenessProbe:
            httpGet:
              port: 8086
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 8086
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
      volumes:
        - name: song-service-app-config
          configMap:
            name: song-service-config-map
            items:
              - key: application.yml
                path: application.yml
