---
apiVersion: v1
kind: ConfigMap
metadata:
  name: song-service-config-map
  namespace: dev-marvel
data:
  application.yml: |
    server:
      port: 8086

    spring:
      application:
        name: song-service
    
    logging:
      level:
        root: info
